version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: contacts-manager-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../public:/var/www
  nginx:
    image: nginx:1.21-alpine
    container_name: contacts-manager-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../public:/var/www
      - ./nginx:/etc/nginx/conf.d